server:
  port: 8080

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

cors:
  originPatterns: http://localhost:3000,http://localhost:8080,http://localhost:80,http://localhost:4200

spring:
  application:
    name: rest-api-with-java

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/rest_api_database?useTimezone=true&serverTimezone=UTC
    username: root
    password: 36412

  flyway:
    url: jdbc:mariadb://127.0.0.1:3306/rest_api_database?useTimezone=true&serverTimezone=UTC
    user: root
    password: 36412

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  output:
    ansi:
      enabled: ALWAYS

springdoc:
  pathsToMatch:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
