server:
  port: 8080
# noinspection undefined
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
# noinspection undefined
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,http://localhost:80,http://localhost:4200
spring:
  application:
    name: rest-api-with-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rest_api_database?useTimezone=true&serverTimezone=UTC
    username: root
    password: 36412
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      ##hibernate:
      ##dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  output:
    ansi:
      #deixa a saída do console colorida
      enabled: ALWAYS
springdoc:
  pathsToMatch:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true