name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # Dispare no push para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'slim'

    - name: Build with Maven
      run: mvn clean package  # Ou './gradlew build' para Gradle

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          athirsonpequeno/api-produtos:latest
